language: ruby
rvm:
 - 2.5
services:
  - postgresql
before_install:
 - cp config/config.yml.sample config/config.yml
 - cp config/database.yml.sample config/database.yml
 - psql -c 'create database cashbox;' -U postgres
